### ISSUE TITLE
使用npm安装^2.2.0的包启动会报 videoSize readonly的错误

### ISSUE THREAD

**Issue by TY-LIU** [Neveryu/rtsp2web#2]
## 发生了什么
使用npm安装了^2.2.0的包，按照demo里面的写法，在启动脚本的时候就会报错
![image](https://user-images.githubusercontent.com/29595097/181481878-d947fc15-0b90-45f3-adae-5cd1d878dfee.png)
我猜测是由于压缩代码导致的问题
错误点：
![image](https://user-images.githubusercontent.com/29595097/181482770-df1c045b-5a5a-4d81-908b-53e41be6f8a2.png)

## 解决方案
* 复制GitHub源码包里面的resource.js 文件到项目中，引入
* 启动成功
![image](https://user-images.githubusercontent.com/29595097/181482473-aa80d410-2aa8-4838-b653-d82a3f14c3df.png)

**Comment by Neveryu** [comment]
是的，或者升级包
