### ISSUE TITLE
node index.js 报错current rtsp2web version: 3.1.2; run on win32

### ISSUE THREAD

**Issue by whanxueyu** [Neveryu/rtsp2web#6]
我的电脑是64位的，安装ffmpeg后按照文档安装了rtsp2web，控制台运行node index.js时报错
current rtsp2web version: 3.1.2; run on win32
请检查你的ffmpeg是否正确存在，错误信息： Error: Command failed: ffmpeg -version
'ffmpeg' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by whanxueyu** [comment]
解决了

**Comment by kujo1717** [comment]
> 

如何解决的？

**Comment by whanxueyu** [comment]
别用编辑器的终端，用电脑自带的终端打开输入命令就行了

**Comment by Neveryu** [comment]
谢谢～

**Comment by Fousaril** [comment]
> 别用编辑器的终端，用电脑自带的终端打开输入命令就行了

我用电脑自带的，还是报这个错误

**Comment by Zhankkkkk** [comment]
> > 别用编辑器的终端，用电脑自带的终端打开输入命令就行了
> 
> 我用电脑自带的，还是报这个错误

我也是，有解决办法吗

**Comment by whanxueyu** [comment]
我记得最后放弃这个方案了














---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 中午11:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Neveryu/rtsp2web] node index.js 报错current rtsp2web version: 3.1.2; run on win32 (Issue #6)




   
别用编辑器的终端，用电脑自带的终端打开输入命令就行了
  
我用电脑自带的，还是报这个错误
  
我也是，有解决办法吗

**Comment by Fousaril** [comment]
谢谢！我换一个方案试试











在 2024-05-22 11:42:04，"Zhankkkkk" ***@***.***> 写道：

别用编辑器的终端，用电脑自带的终端打开输入命令就行了

我用电脑自带的，还是报这个错误

我也是，有解决办法吗
