### ISSUE TITLE
当前端刷新页面后，无法继续播放怎么解决

### ISSUE THREAD

**Issue by xiaoliyooo** [Neveryu/rtsp2web#9]
我使用flv.js播放rtsp视频流，当我刷新页面后会报这样的错误，是和这个插件有关系吗？
![image](https://github.com/Neveryu/rtsp2web/assets/73976311/58dd6445-0fdf-48a9-989d-b2720aeb5fba)
rtsp2web控制台显示这样的提示？大佬我该怎么解决？
![image](https://github.com/Neveryu/rtsp2web/assets/73976311/d82a3bc1-0354-428f-a815-73b0ac783a97)

**Comment by 18845778092** [comment]
换转码库了

**Comment by xiaoliyooo** [comment]
非常痛苦
